name: ProtoPNet
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - tensorboard
  - timm=0.4.12
  - scipy
  - pandas
  - pytorch
  - torchaudio
  - torchvision
  - opencv
  - torchmetrics
  - pip
  - pip:
    - matplotlib==3.5.2
    - tqdm
    - medmnist
    - wandb
    - torchsummary